### PR TITLE
Programs of study

### PR DESCRIPTION
**Pull request by spworky**
Build out Initial  Structure for Programs of Study utilizing Repeatable Card Pattern
– Repeatable Card Structure HTML/CSS – Needs data for 14 areas of Study
– Create an Intro Component to be used as main heading on sub-pages (H1 with sub content .page-title emphasized)
– Create basic JSON file (not fully fleshed out) as potential solution for programs data

### CODE REVIEW

**Comment by pikemurdy** [comment]
I'm getting an error on `nom run dev`

```
error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[5].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[5].use[2]!./node_modules/next/dist/build/webpack/loaders/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[5].use[3]!./node_modules/next/dist/compiled/sass-loader/cjs.js??ruleSet[1].rules[2].oneOf[5].use[4]!./src/scss/components/CTA.module.scss
SassError: Can't find stylesheet to import.
  ╷
3 │ @import 'scss/variables';
  │         ^^^^^^^^^^^^^^^^
  ╵
```

**Comment by MichaelAllenWarner** [comment]
@pikemurdy Looks like several SCSS files were importing the `_variables.scss` partial that you deleted.

**Comment by spworky** [comment]
@pikemurdy @MichaelAllenWarner  Deleting that file is on me. I didn't think anything was using that file since we created the common.scss which imports the full variables.

**Comment by pikemurdy** [comment]
@spworky Okay. See if you can add those back and we'll re-test.

**Comment by spworky** [comment]
@pikemurdy I think this branch now builds correctly. There were a couple of other issues that I had missed before pushing that I think are now resolved.

**Pull request merged**
