### PR TITLE
Styles

### PR DESCRIPTION
**Pull request by pikemurdy**
This would update some of the styling, but not much will actually change until issue [131](https://github.com/utkwdn/utk-atlas/issues/131) is taken care of. And even then, a few things will need to get adjusted.

### CODE REVIEW

**Comment by MichaelAllenWarner** [comment]
@pikemurdy 

Did you mean to target the `development` branch here? It's currently set to `main`.

**Comment by pikemurdy** [comment]
UGH. Yes, I meant development.

**Comment by MichaelAllenWarner** [comment]
@pikemurdy 

I see that there are changes to `package-lock.json` but not to `package.json`. I assume that you weren't trying to install any new npm packages or anything, and that the `package-lock.json` here is simply old (probably your most recent `git pull` in the `development` branch predated some committed changes). So, I figure that we should nix the changes to that file. Sound right to you?

**Comment by pikemurdy** [comment]
Oof. yeah. that sounds right.

**Pull request closed without merging**
